name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  typechecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Setup node.js (for pyright)
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Flake8
        run: |
          poetry install
          poetry run flake8 app --count --show-source --statistics
      - name: Run type checking
        run: |
          npm install -g pyright
          pyright --lib --verifytypes app --ignoreexternal